### PR TITLE
Installation with pip in edit mode

### PR DESCRIPTION
**Pull request by ROBERT-MCDOWELL**
Added files to let the user/developer to install in edit mode (pip install -e .)
- setup.py
- requirements.txt
- pyproject.toml

IMPORTANT: if the app.py is still the script to run it should contain a "__main__" function, otherwise it will be not possible to
call directly ebook2audiobookXTTS as an app name.

Worth to advise the user/develpoer to install a virtual python env v3.10 min, v3.11 max, with for i.e. conda
(I tried with python 3.11 and everything is ok)
conda create --prefix /path/to/env-folder python=3.11
conda activate  /path/to/env-folder
...
conda deactivate

### CODE REVIEW

**Comment by DrewThomasson** [comment]
## WOH! 😲🤩

Dang! you did way more than I would of done!
This is Awesome!

**Comment by ROBERT-MCDOWELL** [comment]
wait. I have to fix some important things yet. next PR ok?

**Comment by DrewThomasson** [comment]
oops, ill revert it

was about to ask about the main thing lol

**Comment by DrewThomasson** [comment]
Reverted

**Comment by ROBERT-MCDOWELL** [comment]
ok I do the fix and run a PR again

**Comment by DrewThomasson** [comment]
I await your updated merge 👍

**Comment by DrewThomasson** [comment]
Hit me up when it's ready

I'm still new to this lol

**Comment by ROBERT-MCDOWELL** [comment]
ok no worries, I'm done for today, tomorrow all will be good

**Pull request merged**
