### PR TITLE
chinese readme

### PR DESCRIPTION
**Pull request by WUYIN66**
add chinese readme

### CODE REVIEW

**Review by DrewThomasson — APPROVED** [review]

**Comment by DrewThomasson** [comment]
# Looks Great! Thank you so much for doing this! 🎉😄


### Oh, how would I write something like 

"For Chinese Readme ----->" [link to Chinese readme]"

In Chinese to add to the top the main readme? 🤔

**Comment by WUYIN66** [comment]
### You can use the link to switch between readme
for example：
image
image

**Comment by DrewThomasson** [comment]
Thats a way better idea lol thx

**Comment by DrewThomasson** [comment]
@WUYIN66 

Do you think you'd be willing to update your Chinese readme to match the major changes we made to the english readme for `ebook2audiobook Version2.0`?

Then I can add put the link to your Chinese readme back in the main English readme again :)

**Comment by WUYIN66** [comment]
ok，if I have time, I will do it.

**Pull request merged**
